  const arenaChallenges=[
    {id:'a1',title:'Give the page a real heading',instruction:'Change the paragraph into an h1 that says Hello, web!',starter:'<p>Hello, web!</p>',hint:'Replace p with h1 in both tags.',validate:c=>/<h1>\s*Hello,\s*web!\s*<\/h1>/i.test(c)},
    {id:'a2',title:'Make the link go somewhere',instruction:'Give the link href="https://example.com".',starter:'<a>Open example</a>',hint:'Attributes go inside the opening tag.',validate:c=>/<a\b[^>]*href=["']https:\/\/example\.com["']/i.test(c)},
    {id:'a3',title:'Make the image accessible',instruction:'Add alt="Mountain at sunrise" to the image.',starter:'<img src="mountain.jpg">',hint:'Add the alt attribute before the >.',validate:c=>{const i=parseHTML(c).querySelector('img');return i?.getAttribute('alt')==='Mountain at sunrise'}},
    {id:'a4',title:'Group the content',instruction:'Put the h2 and p inside a div with class="card".',starter:'<h2>Title</h2>\n<p>Copy.</p>',hint:'Open <div class="card"> before the h2, close it after p.',validate:c=>{const d=parseHTML(c),card=d.querySelector('div.card');return !!card?.querySelector('h2')&&!!card.querySelector('p')}}
  ];
  function updateArenaPreview(){const code=$('#arenaCode').value;$('#arenaPreview').srcdoc=`<!doctype html><html><head><style>body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;padding:28px;color:#1d1d1f}button,input{font:inherit}a{color:#0071e3}</style></head><body>${code}</body></html>`}
  function renderArena(){const c=arenaChallenges[arenaIndex];$('#arenaTitle').textContent=c.title;$('#arenaInstruction').textContent=c.instruction;$('#arenaCode').value=c.starter;$('#arenaFeedback').className='arena-feedback';$('#arenaFeedback p').textContent='Make your change, then check it.';updateArenaPreview()}
  function checkArena(){const c=arenaChallenges[arenaIndex],good=c.validate($('#arenaCode').value),f=$('#arenaFeedback');if(good){f.className='arena-feedback success';f.querySelector('p').textContent=`Correct · x${arenaCombo} combo`;if(!state.arenaCompleted.includes(c.id)){state.arenaCompleted.push(c.id);state.bonusXp+=(20*arenaCombo);saveState()}arenaCombo=Math.min(5,arenaCombo+1);$('#comboValue').textContent=`x${arenaCombo}`;updateHUD();confetti(8);setTimeout(()=>{arenaIndex=(arenaIndex+1)%arenaChallenges.length;renderArena()},850)}else{arenaCombo=1;$('#comboValue').textContent='x1';f.className='arena-feedback error';f.querySelector('p').textContent='Not yet. The requirement is still missing.'}}

  const quizQuestions=[
    {q:'Which tag should normally hold the main page heading?',options:['<h1>','<head>','<title>','<strong>'],answer:0,why:'<h1> is the main heading element.'},
    {q:'Which attribute gives a link its destination?',options:['src','href','alt','class'],answer:1,why:'href tells an <a> element where to go.'},
    {q:'What does alt text do?',options:['Makes an image sharper','Describes an image','Centers an image','Downloads an image'],answer:1,why:'alt describes the image for accessibility and failure cases.'},
    {q:'Which one is usually reusable across many elements?',options:['id','class','title','href'],answer:1,why:'A class is designed to be reused.'},
    {q:'Where does visible page content mainly live?',options:['<meta>','<head>','<body>','<!doctype>'],answer:2,why:'The page people see is inside <body>.'}
  ];
  function newQuizQuestion(){qfAnswered=false;let n;do{n=quizQuestions[Math.floor(Math.random()*quizQuestions.length)]}while(n===qfCurrent&&quizQuestions.length>1);qfCurrent=n;$('#quizCounter').textContent=`Question ${qfScore+1}`;$('#quizQuestion').textContent=n.q;$('#quizResult').textContent='Pick an answer.';const box=$('#quizOptions');box.innerHTML='';n.options.forEach((text,i)=>{const b=document.createElement('button');b.type='button';b.className='quiz-option';b.textContent=text;b.addEventListener('click',()=>answerQuiz(i,b));box.appendChild(b)})}
  function answerQuiz(i,b){if(qfAnswered)return;qfAnswered=true;$$('.quiz-option').forEach((x,j)=>{x.disabled=true;if(j===qfCurrent.answer)x.classList.add('correct')});if(i===qfCurrent.answer){qfScore++;qfCombo=Math.min(9,qfCombo+1);b.classList.add('correct');$('#quizResult').textContent=`Correct. ${qfCurrent.why}`;if(qfXpThisSession<40){qfXpThisSession+=5;state.bonusXp+=5}state.bestQuickfireCombo=Math.max(state.bestQuickfireCombo,qfCombo);saveState();checkPins(true)}else{qfCombo=1;b.classList.add('wrong');$('#quizResult').textContent=`Not this one. ${qfCurrent.why}`}$('#qfScore').textContent=qfScore;$('#qfCombo').textContent=`x${qfCombo}`;updateHUD();setTimeout(newQuizQuestion,1300)}

  function renderRewards(){const defs=[['first','First Steps','Complete your first mission.','1'],['html','HTML Clear','Beat the HTML boss.','<>'],['combo','On a Roll','Reach a 4× Quickfire combo.','4×'],['secret','Source Diver','Find the hidden comment.','<!--'],['builder','Builder','Finish the final build.','✓']];const shelf=$('#rewardShelf');shelf.innerHTML='';defs.forEach(([id,title,desc,mark])=>{const got=state.pins.includes(id),d=document.createElement('div');d.className=`reward-item${got?'':' locked'}`;d.innerHTML=`<div class="pin-mark">${got?esc(mark):'—'}</div><strong>${title}</strong><p>${got?desc:'Locked'}</p>`;shelf.appendChild(d)})}
  function updatePlayground(){const h=$('#htmlEditor').value,c=$('#cssEditor').value;$('#playgroundFrame').srcdoc=`<!doctype html><html><head><style>${c}</style></head><body>${h}</body></html>`;if(!state.secretFound&&/<!--/.test(h)){state.secretFound=true;state.bonusXp+=70;saveState();updateHUD();checkPins(true);showToast('+70 XP · hidden comment found')}}
