  function setup(){
    updateVisit();updateHUD();renderWorld('html');renderRewards();renderArena();newQuizQuestion();updatePlayground();
    $('#continueButton').addEventListener('click',()=>{const n=nextOverallMission();openMission(n.worldKey,n.index,n.custom?n.mission:null)});$('#nextMissionPlay').addEventListener('click',()=>{const n=nextOverallMission();openMission(n.worldKey,n.index,n.custom?n.mission:null)});
    $$('.world-tab').forEach(t=>t.addEventListener('click',()=>{const k=t.dataset.world;if(!worldUnlocked(k)){showToast('Finish the previous world first');return}renderWorld(k)}));
    $('#closeMission').addEventListener('click',()=>$('#missionDialog').close());$('#missionHint').addEventListener('click',()=>{if(currentMission){const f=$('#missionFeedback');f.textContent=`Hint: ${currentMission.hint}`;f.className='mission-feedback'}});$('#missionCheck').addEventListener('click',()=>{if(!currentMission)return;if($('#missionCheck').dataset.done==='true'){proceed();return}const c=$('#missionEditor')?.value||'',f=$('#missionFeedback');let good=false;try{good=!!currentMission.validate(c)}catch{}if(good){f.textContent='Correct. You used the idea properly. ✓';f.className='mission-feedback good';completeMission(currentMission);$('#missionCheck').dataset.done='true';$('#missionCheck').textContent=currentMission.id==='final-build'?'Finish':'Continue →'}else{f.textContent='Not quite. Compare the task with your code, then try again.';f.className='mission-feedback bad'}});
    $('#arenaCode').addEventListener('input',updateArenaPreview);$('#arenaReset').addEventListener('click',renderArena);$('#arenaHint').addEventListener('click',()=>showToast(arenaChallenges[arenaIndex].hint));$('#checkArena').addEventListener('click',checkArena);$('#arenaCode').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();checkArena()}if(e.key==='Tab'){e.preventDefault();const t=e.currentTarget,s=t.selectionStart,en=t.selectionEnd;t.value=t.value.slice(0,s)+'  '+t.value.slice(en);t.selectionStart=t.selectionEnd=s+2;updateArenaPreview()}});
    $('#newQuiz').addEventListener('click',newQuizQuestion);
    $$('.code-tab').forEach(t=>t.addEventListener('click',()=>{$$('.code-tab').forEach(x=>x.classList.toggle('active',x===t));$$('.editor-area').forEach(x=>x.classList.toggle('active',x.dataset.editor===t.dataset.codeTab))}));$('#htmlEditor').addEventListener('input',updatePlayground);$('#cssEditor').addEventListener('input',updatePlayground);$$('.editor-area').forEach(ed=>ed.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const s=ed.selectionStart,en=ed.selectionEnd;ed.value=ed.value.slice(0,s)+'  '+ed.value.slice(en);ed.selectionStart=ed.selectionEnd=s+2;updatePlayground()}}));
    $('#formatPlayground').addEventListener('click',()=>{$('#htmlEditor').value='<main class="card">\n  <p class="tiny">My first page</p>\n  <h1>Hello, web!</h1>\n  <p>I can change this code myself.</p>\n  <button>Nice.</button>\n</main>';$('#cssEditor').value='body {\n  font-family: -apple-system, BlinkMacSystemFont, sans-serif;\n  display: grid;\n  place-items: center;\n  min-height: 100vh;\n  margin: 0;\n  background: #f5f5f7;\n}\n.card {\n  width: min(420px, 80%);\n  padding: 32px;\n  border-radius: 24px;\n  background: white;\n}';updatePlayground();showToast('Playground reset')});
    const surprises=[{h:'<h1>Make something weird.</h1>\n<p>The browser is a canvas.</p>',c:'body{font-family:-apple-system,sans-serif;padding:60px;background:#111;color:#fff}h1{font-size:64px;letter-spacing:-.06em;max-width:600px}p{color:#aaa}'},{h:'<button class="pill">Press me</button>',c:'body{min-height:100vh;margin:0;display:grid;place-items:center;background:#f5f5f7}.pill{border:0;border-radius:999px;padding:14px 20px;background:#111;color:#fff;font:600 15px -apple-system;transition:.2s}.pill:active{transform:scale(.94)}'},{h:'<!-- secret found -->\n<h1>You found the hidden comment.</h1>\n<p>Comments are visible in code, not on the rendered page.</p>',c:'body{font-family:-apple-system,sans-serif;padding:40px}h1{font-size:42px;letter-spacing:-.04em}p{color:#6e6e73}'}];$('#surpriseMe').addEventListener('click',()=>{const x=surprises[Math.floor(Math.random()*surprises.length)];$('#htmlEditor').value=x.h;$('#cssEditor').value=x.c;updatePlayground();showToast('New experiment loaded')});
    $('#finalBossButton').addEventListener('click',()=>{if(worldComplete('html'))openMission('html',0,finalMission)});
    $('#profileButton').addEventListener('click',()=>$('#profileDialog').showModal());$('#closeProfile').addEventListener('click',()=>$('#profileDialog').close());$('#saveProfile').addEventListener('click',()=>{state.name=$('#profileNameInput').value.trim()||'Learner';saveState();updateHUD();$('#profileDialog').close();showToast('Saved')});$('#resetProgress').addEventListener('click',()=>{if(!confirm('Reset all progress on this browser?'))return;state={...defaultState,lastVisit:today(),todayDate:today()};saveState();updateHUD();renderWorld('html');renderRewards();$('#profileDialog').close();showToast('Progress reset')});$('#claimReward').addEventListener('click',()=>$('#rewardDialog').close());
    const mb=$('#menuButton'),mm=$('#mobileMenu');mb.addEventListener('click',()=>{const o=mm.classList.toggle('open');mb.setAttribute('aria-expanded',String(o));mm.setAttribute('aria-hidden',String(!o))});$$('a',mm).forEach(a=>a.addEventListener('click',()=>{mm.classList.remove('open');mb.setAttribute('aria-expanded','false');mm.setAttribute('aria-hidden','true')}));
    window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;$('#pageProgress').style.width=`${max>0?scrollY/max*100:0}%`},{passive:true});
    if(matchMedia('(prefers-reduced-motion: reduce)').matches)$$('.reveal').forEach(x=>x.classList.add('visible'));else{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(x=>io.observe(x))}
  }
  setup();
