  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const STORAGE_KEY='htmlGuideProgressV3';

  const parseHTML=code=>new DOMParser().parseFromString(code,'text/html');
  const missions={
    html:[
      {id:'html-0',title:'Meet your first tag',time:'2 min',xp:40,intro:'HTML tells the browser what each piece of a page is.',conceptTitle:'A tag wraps content',explanation:'Most elements have an opening tag, some content, and a closing tag. The slash means the element ends here.',example:'<h1>Hello, web!</h1>',task:'Create an <h1> that says “Hello, web!”',starter:'<p>Hello, web!</p>',hint:'Change both p tags into h1 tags.',validate:c=>/<h1\b[^>]*>\s*Hello,\s*web!\s*<\/h1>/i.test(c)},
      {id:'html-1',title:'Say more with text',time:'3 min',xp:45,intro:'Headings give structure. Paragraphs carry normal text.',conceptTitle:'Use the right text element',explanation:'Use <h1> for the main heading and <p> for normal paragraphs. <strong> marks important text.',example:'<h1>My page</h1>\n<p>I am learning <strong>HTML</strong>.</p>',task:'Wrap the word HTML in a <strong> tag inside the paragraph.',starter:'<h1>My page</h1>\n<p>I am learning HTML.</p>',hint:'Turn HTML into <strong>HTML</strong>.',validate:c=>/<p\b[^>]*>[\s\S]*<strong\b[^>]*>\s*HTML\s*<\/strong>[\s\S]*<\/p>/i.test(c)},
      {id:'html-2',title:'Make a real link',time:'3 min',xp:50,intro:'Links connect pages. An attribute gives the link its destination.',conceptTitle:'Attributes add information',explanation:'href lives inside the opening <a> tag and tells the browser where the link goes.',example:'<a href="https://example.com">Visit example</a>',task:'Make “Open site” link to https://example.com.',starter:'<a>Open site</a>',hint:'Add href="https://example.com" inside the opening tag.',validate:c=>/<a\b[^>]*href=["']https:\/\/example\.com\/?["'][^>]*>\s*Open site\s*<\/a>/i.test(c)},
      {id:'html-3',title:'Nest a card',time:'4 min',xp:55,intro:'Real pages contain elements inside other elements.',conceptTitle:'Parents contain children',explanation:'A <div> is a generic container. Indentation makes the structure easier to read.',example:'<div class="card">\n  <h2>Headphones</h2>\n  <p>Wireless audio.</p>\n  <button>View</button>\n</div>',task:'Put the h2, p and button inside one <div class="card">.',starter:'<h2>Headphones</h2>\n<p>Wireless audio.</p>\n<button>View</button>',hint:'Open the div before h2 and close it after the button.',validate:c=>{const d=parseHTML(c),card=d.querySelector('div.card');return !!card&&!!card.querySelector('h2')&&!!card.querySelector('p')&&!!card.querySelector('button')}},
      {id:'html-4',title:'Classes and IDs',time:'4 min',xp:60,intro:'CSS and JavaScript need reliable names for elements.',conceptTitle:'Class = reusable. ID = unique.',explanation:'Use class when many elements can share a style. Use id for one specific element.',example:'<button class="action" id="primary">Save</button>',task:'Give both buttons class="action" and only the first id="primary".',starter:'<button>Save</button>\n<button>Cancel</button>',hint:'First: class="action" id="primary". Second: class="action".',validate:c=>{const b=[...parseHTML(c).querySelectorAll('button')];return b.length>=2&&b[0].classList.contains('action')&&b[1].classList.contains('action')&&b[0].id==='primary'}},
      {id:'html-5',title:'Images that make sense',time:'4 min',xp:65,intro:'Images need both a source and useful alternative text.',conceptTitle:'src loads it. alt explains it.',explanation:'alt helps screen readers and also explains the image when it cannot load.',example:'<img src="cat.jpg" alt="Orange cat sleeping">',task:'Set src="avatar.png" and alt="Profile picture".',starter:'<img>',hint:'Add both src and alt attributes.',validate:c=>{const i=parseHTML(c).querySelector('img');return !!i&&i.getAttribute('src')==='avatar.png'&&i.getAttribute('alt')?.trim().toLowerCase()==='profile picture'}},
      {id:'html-6',title:'Build a form',time:'5 min',xp:70,intro:'Forms collect information from people.',conceptTitle:'Native controls do real work',explanation:'Use an email input for email and a submit button to submit the form.',example:'<form>\n  <input type="email">\n  <button type="submit">Join</button>\n</form>',task:'Create a form with an email input and a submit button.',starter:'<form>\n  <!-- add controls -->\n</form>',hint:'Add <input type="email"> and <button type="submit">Join</button>.',validate:c=>{const f=parseHTML(c).querySelector('form');return !!f?.querySelector('input[type="email"]')&&!!f.querySelector('button[type="submit"]')}},
      {id:'html-7',title:'HTML Boss: real structure',time:'7 min',xp:120,boss:true,intro:'Build the meaningful skeleton of a real page.',conceptTitle:'Semantic HTML describes purpose',explanation:'header, nav, main, section and footer describe what each region of the page is for.',example:'<header>...</header>\n<main>\n  <section>...</section>\n</main>\n<footer>...</footer>',task:'Create header > nav, main > section > h1, and a footer.',starter:'<!-- Build the page skeleton -->\n',hint:'Use <header><nav>...</nav></header>, then main/section/h1, then footer.',validate:c=>{const d=parseHTML(c);return !!d.querySelector('header nav')&&!!d.querySelector('main section h1')&&!!d.querySelector('footer')}}
    ],
    css:[
      {id:'css-0',title:'Your first style',time:'3 min',xp:50,intro:'CSS changes how HTML looks.',conceptTitle:'Selector → property → value',explanation:'The selector chooses an element. The property says what changes. The value says how.',example:'h1 {\n  color: royalblue;\n}',task:'Make the h1 color royalblue.',starter:'h1 {\n  color: black;\n}',hint:'Change black to royalblue.',validate:c=>/h1\s*\{[\s\S]*color\s*:\s*royalblue/i.test(c)},
      {id:'css-1',title:'Space is design',time:'4 min',xp:55,intro:'Good spacing does more for UI than random effects.',conceptTitle:'Padding lives inside the box',explanation:'padding creates breathing room inside an element. border-radius rounds corners.',example:'.card {\n  padding: 24px;\n  border-radius: 20px;\n}',task:'Give .card 24px padding and 20px border radius.',starter:'.card {\n  padding: 0;\n}',hint:'Add padding: 24px; and border-radius: 20px;',validate:c=>/\.card\s*\{[\s\S]*padding\s*:\s*24px[\s\S]*border-radius\s*:\s*20px/i.test(c)},
      {id:'css-2',title:'Flex the layout',time:'5 min',xp:65,intro:'Flexbox is one of the most useful layout systems on the web.',conceptTitle:'display:flex lines children up',explanation:'gap adds consistent space between flex items.',example:'.actions {\n  display: flex;\n  gap: 12px;\n}',task:'Turn .actions into flex with a 12px gap.',starter:'.actions {\n\n}',hint:'Add display: flex; and gap: 12px;',validate:c=>/\.actions\s*\{[\s\S]*display\s*:\s*flex[\s\S]*gap\s*:\s*12px/i.test(c)},
      {id:'css-3',title:'Make it respond',time:'5 min',xp:70,intro:'Interaction should feel responsive, not static.',conceptTitle:'Pseudo-classes describe states',explanation:':hover applies styles while the pointer is over an element.',example:'.button:hover { transform: scale(1.04); }',task:'On hover, scale .button to 1.04.',starter:'.button:hover {\n\n}',hint:'Add transform: scale(1.04);',validate:c=>/\.button:hover\s*\{[\s\S]*transform\s*:\s*scale\(1\.04\)/i.test(c)},
      {id:'css-4',title:'Fit every screen',time:'6 min',xp:80,intro:'Responsive design adapts to the screen.',conceptTitle:'Media queries add conditional styles',explanation:'@media can apply a layout only when the screen is narrow enough.',example:'@media (max-width: 700px) {\n  .grid { grid-template-columns: 1fr; }\n}',task:'At 700px or below, make .grid use one column.',starter:'@media (max-width: 700px) {\n  .grid {\n  }\n}',hint:'Add grid-template-columns: 1fr;',validate:c=>/@media\s*\([^)]*max-width\s*:\s*700px[^)]*\)[\s\S]*grid-template-columns\s*:\s*1fr/i.test(c)},
      {id:'css-5',title:'CSS Boss: card system',time:'8 min',xp:130,boss:true,intro:'Build a tiny reusable design system.',conceptTitle:'Consistency beats decoration',explanation:'Reuse spacing, radius and interaction patterns instead of styling every thing randomly.',example:'.card { padding:24px; border-radius:20px; }\n.card:hover { transform:translateY(-2px); }',task:'Give .card 24px padding, 20px radius, white background and hover translateY(-2px).',starter:'.card {\n\n}\n\n.card:hover {\n\n}',hint:'Use padding, border-radius, background, then a hover transform.',validate:c=>/\.card\s*\{[\s\S]*padding\s*:\s*24px[\s\S]*border-radius\s*:\s*20px[\s\S]*background\s*:\s*(white|#fff(?:fff)?)[\s\S]*\}[\s\S]*\.card:hover\s*\{[\s\S]*translateY\(-2px\)/i.test(c)}
    ],
    js:[
      {id:'js-0',title:'Store a value',time:'3 min',xp:50,intro:'JavaScript adds behavior. Variables let it remember values.',conceptTitle:'const names a value',explanation:'Use const when you do not plan to reassign the variable.',example:'const name = "Learner";',task:'Create const name with the value "Learner".',starter:'// write the variable\n',hint:'const name = "Learner";',validate:c=>/const\s+name\s*=\s*["']Learner["']/i.test(c)},
      {id:'js-1',title:'Make a function',time:'4 min',xp:60,intro:'Functions package instructions.',conceptTitle:'A function is reusable behavior',explanation:'Define a function once, then call it whenever you need it.',example:'function greet() {\n  console.log("Hello!");\n}',task:'Create a function named greet.',starter:'function () {\n  console.log("Hello!");\n}',hint:'Put greet before the parentheses.',validate:c=>/function\s+greet\s*\(\s*\)/i.test(c)},
      {id:'js-2',title:'Find an element',time:'4 min',xp:65,intro:'JavaScript needs a way to find HTML.',conceptTitle:'querySelector uses CSS selectors',explanation:'document.querySelector(".card") finds the first element with class card.',example:'const card = document.querySelector(".card");',task:'Create const button by selecting .button.',starter:'const button = document.querySelector("");',hint:'Put .button inside the quotes.',validate:c=>/const\s+button\s*=\s*document\.querySelector\(\s*["']\.button["']\s*\)/i.test(c)},
      {id:'js-3',title:'Listen for a click',time:'5 min',xp:75,intro:'Events let your page react to people.',conceptTitle:'addEventListener listens for behavior',explanation:'Listen for a click, then run a function when it happens.',example:'button.addEventListener("click", () => {\n  console.log("clicked");\n});',task:'Add a click event listener to button.',starter:'button.',hint:'Use button.addEventListener("click", () => {});',validate:c=>/button\.addEventListener\(\s*["']click["']/i.test(c)},
      {id:'js-4',title:'JavaScript Boss: toggle a class',time:'8 min',xp:140,boss:true,intro:'Combine selecting an element, listening for a click and changing a class.',conceptTitle:'classList connects JavaScript to CSS state',explanation:'classList.toggle adds the class if missing and removes it if present.',example:'button.addEventListener("click", () => {\n  document.body.classList.toggle("dark");\n});',task:'On button click, toggle the class dark on document.body.',starter:'const button = document.querySelector("button");\n\n',hint:'Add a click listener and call document.body.classList.toggle("dark").',validate:c=>/addEventListener\(\s*["']click["'][\s\S]*document\.body\.classList\.toggle\(\s*["']dark["']/i.test(c)}
    ]
  };
  const worlds={html:{number:'WORLD 1',title:'HTML Foundations',description:'Build the skeleton of the web from absolute zero.'},css:{number:'WORLD 2',title:'CSS Styling',description:'Turn structure into thoughtful interface design.'},js:{number:'WORLD 3',title:'JavaScript Behavior',description:'Make the page react and do things.'}};
  const finalMission={id:'final-build',title:'Zero → Website',time:'15–30 min',xp:180,boss:true,intro:'Build a small page from a blank file.',conceptTitle:'Put the fundamentals together',explanation:'Use meaningful structure, a link, an image with alt text and a form control. The exact design is yours.',example:'<header>...</header>\n<main>...</main>\n<footer>...</footer>',task:'Build a page with header, nav, main, section, h1, a link, an image with alt text and a form control.',starter:'<!-- Start from blank -->\n',hint:'Build the semantic skeleton first, then add the link, image and form.',validate:c=>{const d=parseHTML(c);return !!d.querySelector('header nav')&&!!d.querySelector('main section h1')&&!!d.querySelector('a[href]')&&!!d.querySelector('img[alt]:not([alt=""])')&&!!d.querySelector('form input, form textarea, form select')}};
