  const allMissions=[...missions.html,...missions.css,...missions.js,finalMission];
  const totalCourseXp=[...missions.html,...missions.css,...missions.js].reduce((s,m)=>s+m.xp,0);
  const totalCourseMissions=missions.html.length+missions.css.length+missions.js.length;
  const defaultState={name:'Learner',completed:[],bonusXp:0,pins:[],streak:1,lastVisit:'',todayDate:'',todayCount:0,dailyRewardDate:'',arenaCompleted:[],bestQuickfireCombo:1,secretFound:false};
  let state=loadState(), currentWorld='html', currentMission=null,currentMissionWorld='html',currentMissionIndex=0,arenaIndex=0,arenaCombo=1,qfCurrent=null,qfScore=0,qfCombo=1,qfAnswered=false,qfXpThisSession=0;

  function loadState(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return {...defaultState,...(raw||{}),completed:Array.isArray(raw?.completed)?raw.completed:[],pins:Array.isArray(raw?.pins)?raw.pins:[],arenaCompleted:Array.isArray(raw?.arenaCompleted)?raw.arenaCompleted:[]}}catch{return {...defaultState}}}
  function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
  function missionById(id){return allMissions.find(m=>m.id===id)}
  function curriculumXp(){return state.completed.reduce((s,id)=>{const m=missionById(id);return s+(m&&m.id!=='final-build'?m.xp:0)},0)}
  function totalXp(){return curriculumXp()+(Number(state.bonusXp)||0)+(state.completed.includes('final-build')?finalMission.xp:0)}
  function courseProgress(){return Math.min(100,Math.round((curriculumXp()/totalCourseXp)*100))}
  function levelInfo(){const xp=totalXp(),step=250,level=Math.floor(xp/step)+1;return {xp,level,within:xp%step,next:step}}
  function worldComplete(key){return missions[key].every(m=>state.completed.includes(m.id))}
  function worldUnlocked(key){return key==='html'||(key==='css'&&worldComplete('html'))||(key==='js'&&worldComplete('css'))}
  function missionUnlocked(key,index){return worldUnlocked(key)&&(index===0||state.completed.includes(missions[key][index-1].id))}
  function nextOverallMission(){for(const key of ['html','css','js']){if(!worldUnlocked(key))continue;const i=missions[key].findIndex(m=>!state.completed.includes(m.id));if(i>=0)return {worldKey:key,index:i,mission:missions[key][i]}}return {worldKey:'html',index:0,mission:finalMission,custom:true}}
  const today=()=>new Date().toISOString().slice(0,10);
  function updateVisit(){const t=today();if(state.todayDate!==t){state.todayDate=t;state.todayCount=0}if(state.lastVisit&&state.lastVisit!==t){const d=(new Date(t+'T00:00:00Z')-new Date(state.lastVisit+'T00:00:00Z'))/86400000;state.streak=d===1?Math.max(1,state.streak+1):1}else if(!state.lastVisit)state.streak=1;state.lastVisit=t;saveState()}
  function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),1700)}
  function addBonusXp(amount,reason){state.bonusXp=Math.max(0,(Number(state.bonusXp)||0)+amount);saveState();updateHUD();showToast(`+${amount} XP · ${reason}`)}
  function confetti(count=16){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<count;i++){const e=document.createElement('i');e.style.cssText=`position:fixed;z-index:2000;left:${45+Math.random()*10}%;top:48%;width:${4+Math.random()*4}px;height:${4+Math.random()*4}px;background:${['#0071e3','#30a14e','#ff9f0a','#1d1d1f'][i%4]};border-radius:2px;pointer-events:none;transition:transform .8s cubic-bezier(.15,.8,.2,1),opacity .8s`;document.body.appendChild(e);requestAnimationFrame(()=>{e.style.transform=`translate(${(Math.random()-.5)*360}px,${-80-Math.random()*280}px) rotate(${Math.random()*540}deg)`;e.style.opacity='0'});setTimeout(()=>e.remove(),850)}}
  function checkPins(show=false){const defs=[['first','First Steps','Complete your first mission.',()=>state.completed.length>=1],['html','HTML Clear','Beat the HTML boss.',()=>worldComplete('html')],['combo','On a Roll','Reach a 4× Quickfire combo.',()=>state.bestQuickfireCombo>=4],['builder','Builder','Finish the final build.',()=>state.completed.includes('final-build')],['secret','Source Diver','Find the hidden HTML comment.',()=>state.secretFound]];for(const [id,title,desc,ok] of defs){if(ok()&&!state.pins.includes(id)){state.pins.push(id);saveState();if(show){$('#rewardTitle').textContent=title;$('#rewardDescription').textContent=desc;$('#rewardDialog').showModal();confetti(22)}}}renderRewards()}
  function updateHUD(){const p=courseProgress(),li=levelInfo(),done=state.completed.filter(id=>missionById(id)&&id!=='final-build').length,next=nextOverallMission();$('#navProgress').textContent=`${p}%`;$('#navXp').textContent=`${li.xp} XP`;$('#navCourseBar').style.width=`${p}%`;$('#heroCoursePercent').textContent=`${p}%`;$('#courseProgressTrack').style.setProperty('--progress',p);$('#heroMissionCount').textContent=`${done} of ${totalCourseMissions} missions`;$('#heroLevel').textContent=`Level ${li.level}`;$('#nextMissionTitle').textContent=next.custom?'Final build':next.mission.title;$('#nextMissionMeta').textContent=`${next.mission.time} · ${next.mission.xp} XP`;$('#dailyMissionProgress').textContent=Math.min(2,state.todayCount||0);$('#heroStreak').textContent=state.streak||1;$('#profileHeading').textContent=state.name||'Learner';$('#profileNameInput').value=state.name||'Learner';$('#profileCoursePercent').textContent=`${p}%`;$('#profileCourseBar').style.width=`${p}%`;$('#profileXp').textContent=li.xp;$('#profileCompleted').textContent=done;$('#profileStreak').textContent=state.streak||1;const boss=$('#finalBossButton');if(worldComplete('html')){boss.disabled=false;boss.textContent=state.completed.includes('final-build')?'Final build complete ✓':'Start final build';$('#bossLock').textContent=state.completed.includes('final-build')?'Complete':'Unlocked'}else{boss.disabled=true;boss.textContent='Locked · finish HTML first';$('#bossLock').textContent='Locked'}}

  function renderWorld(key=currentWorld){currentWorld=key;if(!worldUnlocked(key)){showToast('Finish the previous world first');key=currentWorld='html'}$$('.world-tab').forEach(t=>{const k=t.dataset.world,locked=!worldUnlocked(k);t.classList.toggle('active',k===key);t.classList.toggle('locked',locked);t.setAttribute('aria-selected',String(k===key));t.setAttribute('aria-disabled',String(locked))});const meta=worlds[key],list=missions[key];$('#worldNumber').textContent=meta.number;$('#worldTitle').textContent=meta.title;$('#worldDescription').textContent=meta.description;const done=list.filter(m=>state.completed.includes(m.id)).length;$('#worldProgressPercent').textContent=`${Math.round(done/list.length*100)}%`;const path=$('#questPath');path.innerHTML='';list.forEach((m,i)=>{const unlocked=missionUnlocked(key,i),completed=state.completed.includes(m.id),current=unlocked&&!completed&&(i===0||state.completed.includes(list[i-1].id));const b=document.createElement('button');b.type='button';b.className=`mission-row${completed?' done':''}${current?' current':''}${m.boss?' boss':''}`;b.disabled=!unlocked;b.innerHTML=`<span class="mission-node">${completed?'✓':m.boss?'★':i+1}</span><span class="mission-copy"><strong>${m.title}</strong><small>${m.time} · ${m.xp} XP${m.boss?' · Boss':''}</small></span><span class="mission-right">${completed?'Complete':unlocked?'Open':'Locked'}</span>`;b.addEventListener('click',()=>openMission(key,i));path.appendChild(b)})}
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  function syntaxExample(s){return esc(s)}
  function openMission(key,index,custom=null){const world=worlds[key]||worlds.html,m=custom||missions[key][index];if(!m)return;currentMission=m;currentMissionWorld=key;currentMissionIndex=index;const total=custom?1:missions[key].length,display=custom?1:index+1;$('#missionXpPill').textContent=`+${m.xp} XP`;$('#missionProgressBar').style.width=`${display/total*100}%`;$('#missionIntro').innerHTML=`<span class="mission-count">${custom?'FINAL BUILD':`${world.number} · MISSION ${display}/${total}`}</span><h2>${esc(m.title)}</h2><p>${esc(m.intro)}</p>`;$('#missionLesson').innerHTML=`<div class="learn-card"><span>THE IDEA</span><h3>${esc(m.conceptTitle)}</h3><p>${esc(m.explanation)}</p></div><pre class="learn-code"><code>${syntaxExample(m.example)}</code></pre>`;$('#missionTask').innerHTML=`<div class="mission-task-head"><span>YOUR TURN</span><h3>${esc(m.task)}</h3><p>Change the code below. Try as many times as you need.</p></div><div class="mission-editor-wrap"><div class="panel-bar"><span>${key==='css'?'style.css':key==='js'?'script.js':'index.html'}</span><span>Editable</span></div><textarea id="missionEditor" spellcheck="false">${esc(m.starter)}</textarea></div><div class="mission-feedback" id="missionFeedback" aria-live="polite">Nothing is submitted until you press Check answer.</div>`;const completed=state.completed.includes(m.id);$('#missionCheck').dataset.done=String(completed);$('#missionCheck').textContent=completed?'Completed · Continue':'Check answer';$('#missionDialog').showModal();setTimeout(()=>$('#missionEditor')?.focus(),80)}
  function completeMission(m){if(state.completed.includes(m.id))return false;state.completed.push(m.id);state.todayCount=(state.todayCount||0)+1;saveState();if(state.todayCount>=2&&state.dailyRewardDate!==today()){state.dailyRewardDate=today();state.bonusXp+=50;showToast('+50 XP · daily quest')}checkPins(true);updateHUD();renderWorld(currentMissionWorld);confetti(m.boss?26:12);return true}
  function proceed(){const m=currentMission;$('#missionDialog').close();updateHUD();if(!m||m.id==='final-build')return;const list=missions[currentMissionWorld],next=currentMissionIndex+1;if(next<list.length)setTimeout(()=>openMission(currentMissionWorld,next),160);else if(currentMissionWorld==='html')showToast('HTML complete · CSS unlocked');else if(currentMissionWorld==='css')showToast('CSS complete · JavaScript unlocked')}
